# Generated by Django 5.1.1 on 2024-10-03 01:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloTarificacion',
            fields=[
                ('id_ciclo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CodigoUnidad',
            fields=[
                ('id_codigo_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_unidad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPresupuestaria',
            fields=[
                ('id_cuenta_presupuestaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuenta_presupuestaria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorTelefonia',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=40)),
                ('tarifa_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_slm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_ldi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('correo_electronico_usuario', models.EmailField(max_length=254, unique=True)),
                ('rol_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Responsable de Unidad', 'Responsable de Unidad')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_anexo', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('codigo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.codigounidad')),
            ],
        ),
        migrations.AddField(
            model_name='codigounidad',
            name='cuenta_presupuestaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.cuentapresupuestaria'),
        ),
        migrations.AddField(
            model_name='codigounidad',
            name='proveedor_telefonia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tarificacion.proveedortelefonia'),
        ),
        migrations.CreateModel(
            name='Tarificacion',
            fields=[
                ('id_tarificacion', models.AutoField(primary_key=True, serialize=False)),
                ('total_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_slm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ldi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.anexo')),
                ('ciclo_tarificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.ciclotarificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id_llamada', models.AutoField(primary_key=True, serialize=False)),
                ('origen_llamada', models.CharField(max_length=20)),
                ('destino_llamada', models.CharField(max_length=20)),
                ('caller_id_llamada', models.CharField(blank=True, max_length=50, null=True)),
                ('aplicacion_llamada', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('duracion_llamada', models.IntegerField()),
                ('tiempo_billing', models.IntegerField()),
                ('disposicion_llamada', models.CharField(blank=True, max_length=20, null=True)),
                ('proveedor_telefonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.proveedortelefonia')),
                ('tarificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.tarificacion')),
            ],
        ),
    ]
