# Generated by Django 5.1.1 on 2024-10-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CicloTarificacion',
            new_name='Ciclo',
        ),
        migrations.RenameModel(
            old_name='CodigoUnidad',
            new_name='CodUnidad',
        ),
        migrations.RenameModel(
            old_name='CuentaPresupuestaria',
            new_name='CtaPresu',
        ),
        migrations.RenameModel(
            old_name='ProveedorTelefonia',
            new_name='Proveedor',
        ),
    ]
