# Generated by Django 5.1.1 on 2024-10-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0006_alter_anexo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anexo',
            table='ADMIN.app_tarificacion_anexo',
        ),
    ]
