# Generated by Django 5.1.1 on 2024-10-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0008_alter_anexo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarificacion',
            name='ciclo_tarificacion',
        ),
        migrations.DeleteModel(
            name='Ciclo',
        ),
    ]
