# Generated by Django 5.1.1 on 2024-10-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0010_tarificacion_codigo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarificacion',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.anexo'),
        ),
    ]
