# Generated by Django 5.1.1 on 2024-10-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0011_alter_tarificacion_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarificacion',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='codunidad',
            name='cuenta_presupuestaria',
        ),
        migrations.RemoveField(
            model_name='codunidad',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='tarificacion',
            name='codigo_unidad',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='proveedor_telefonia',
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='tarificacion',
        ),
        migrations.DeleteModel(
            name='Anexo',
        ),
        migrations.DeleteModel(
            name='CtaPresu',
        ),
        migrations.DeleteModel(
            name='CodUnidad',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Llamada',
        ),
        migrations.DeleteModel(
            name='Tarificacion',
        ),
    ]
