# Generated by Django 5.1.1 on 2024-10-15 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tarificacion', '0012_remove_tarificacion_anexo_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codunidad',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_codigo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ctapresu',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
                ('tarifa_cel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_slm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifa_ldi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_anexo', models.IntegerField()),
                ('cargo_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_anexo', models.CharField(max_length=30)),
                ('codunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.codunidad')),
            ],
        ),
        migrations.AddField(
            model_name='codunidad',
            name='ctapresu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.ctapresu'),
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id_llamada', models.AutoField(primary_key=True, serialize=False)),
                ('origen_llamada', models.IntegerField()),
                ('destino_llamada', models.IntegerField()),
                ('identificador_llamada', models.IntegerField()),
                ('app_llamada', models.CharField(max_length=30)),
                ('inicio_llamada', models.DateTimeField()),
                ('duracion_llamada', models.IntegerField()),
                ('segundos_facturados', models.IntegerField()),
                ('disposicion', models.CharField(max_length=30)),
                ('tipo_llamada', models.CharField(max_length=20)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.anexo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Tarificacion',
            fields=[
                ('id_tarificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minutos_totales', models.IntegerField()),
                ('tipo_llamada', models.CharField(max_length=20)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.anexo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol_usuario', models.CharField(max_length=30)),
                ('email_usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anexo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tarificacion.usuario'),
        ),
    ]
