# Generated by Django 5.1.1 on 2024-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
