# Generated by Django 5.1.1 on 2024-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0014_alter_usuario_email_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
