# Generated by Django 5.1.1 on 2024-11-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0015_alter_usuario_email_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codunidad',
            name='nombre_codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ctapresu',
            name='nombre_cuenta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
