# Generated by Django 5.1.1 on 2024-11-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarificacion', '0016_alter_codunidad_nombre_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='inicio_llamada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarificacion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarificacion',
            name='fecha_termino',
            field=models.DateField(),
        ),
    ]
